# Generated by Django 4.2.6 on 2023-11-01 17:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True, verbose_name='Название меню')),
                ('named_url', models.CharField(blank=True, max_length=255, verbose_name='Именованный URL')),
            ],
            options={
                'verbose_name': 'Меню',
                'verbose_name_plural': 'Меню',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=100, null=True, verbose_name='Slug')),
                ('name', models.CharField(max_length=50, verbose_name='Название пункта меню')),
                ('named_url', models.CharField(blank=True, max_length=255, verbose_name='Именованный URL')),
                ('url', models.CharField(blank=True, max_length=255, verbose_name='Ссылка')),
                ('level', models.IntegerField(default=0, verbose_name='Уровень')),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='menu.menu', verbose_name='Меню')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='menu.menuitem')),
            ],
            options={
                'verbose_name': 'Пункт меню',
                'verbose_name_plural': 'Пункты меню',
                'ordering': ['menu', 'level', 'name'],
            },
        ),
    ]
