# Generated by Django 4.2.6 on 2023-10-31 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menu',
            name='url',
        ),
        migrations.AddField(
            model_name='menu',
            name='named_url',
            field=models.CharField(blank=True, max_length=255, verbose_name='Именованный URL'),
        ),
    ]
