# Generated by Django 4.2.6 on 2023-10-31 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0003_alter_menuitem_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='level',
            field=models.IntegerField(default=0, verbose_name='Уровень'),
        ),
    ]
