# Generated by Django 4.2.6 on 2023-11-01 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0005_alter_menuitem_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='slug',
            field=models.SlugField(max_length=100, null=True, verbose_name='Slug'),
        ),
    ]
